#
# (c) Copyright 2021 Micro Focus or one of its affiliates.
#
# Licensed under the MIT License (the "License"); you may not use this file
# except in compliance with the License.
#
# The only warranties for products and services of Micro Focus and its affiliates
# and licensors ("Micro Focus") are as may be set forth in the express warranty
# statements accompanying such products and services. Nothing herein should be
# construed as constituting an additional warranty. Micro Focus shall not be
# liable for technical or editorial errors or omissions contained herein. The
# information contained herein is subject to change without notice.
#

services:

  entity-indexdb:
    image: ${ISOL_DOCKER_REGISTRY}${ISOL_DOCKER_NAME_SEP}solutions-entity-indexdb${ISOL_DOCKER_VERSION_SEP}${ISOL_BASE_VERSION}
    networks:
      - main
    volumes:
      - entity-indexdb-data:/content/index
    ports:
      - ${ISOL_ENTITY_INDEXDB_ACI_DOCKER_PORT}:9100
      - ${ISOL_ENTITY_INDEXDB_INDEX_DOCKER_PORT}:9101
    environment:
      - ISOL_LICENSE_SERVER_HOST=${ISOL_LICENSE_SERVER_HOST}
      - ISOL_LICENSE_SERVER_PORT=${ISOL_LICENSE_SERVER_PORT}
      - ISOL_ENTITY_INDEXDB_CFG=${ISOL_ENTITY_INDEXDB_CFG}

  entity-storagedb:
    image: ${ISOL_DOCKER_REGISTRY}${ISOL_DOCKER_NAME_SEP}solutions-entity-storagedb${ISOL_DOCKER_VERSION_SEP}${ISOL_BASE_VERSION}
    networks:
      - main
    volumes:
      - entity-storagedb-data:/var/lib/cassandra
    ports:
      - ${ISOL_ENTITY_STORAGEDB_DOCKER_PORT}:9042
    environment:
      - MAX_HEAP_SIZE=${ISOL_ENTITY_STORAGEDB_MAX_HEAP_SIZE}
      - HEAP_NEWSIZE=${ISOL_ENTITY_STORAGEDB_HEAP_NEWSIZE}

  entity-service:
    image: ${ISOL_DOCKER_REGISTRY}${ISOL_DOCKER_NAME_SEP}solutions-entity-service${ISOL_DOCKER_VERSION_SEP}${ISOL_VERSION}
    networks:
      - main
    volumes:
      - entity-schemadb-data:/var/lib/janusgraph
    ports:
      - ${ISOL_ENTITY_SERVICE_DOCKER_PORT}:8182
    environment:
      - ISOL_ENTITY_STORAGEDB_HOST=entity-storagedb
      - ISOL_ENTITY_STORAGEDB_PORT=9042
      - ISOL_ENTITY_INDEXDB_HOST=entity-indexdb
      - ISOL_ENTITY_INDEXDB_ACI_PORT=9100
      - ISOL_ENTITY_INDEXDB_INDEX_PORT=9101

volumes:
  entity-schemadb-data:
  entity-storagedb-data:
  entity-indexdb-data:
